#if defined(DC_PLATFORM_ANDROID)
#include <jni.h>
#include <android/asset_manager_jni.h>
#include "runtime/Application.h"

extern JNIEnv* g_env;
extern jobject g_jni_obj;

//解压资源
DC_BEGIN_NAMESPACE
static void extract_assets(jobject asset_manager, const String& source, const String& dest)
{
    auto mgr = AAssetManager_fromJava(g_env, asset_manager);
    Vector<String> files;

    // file_list.txt is generated by copy_assets.py script.
    auto asset = AAssetManager_open(mgr, "file_list.txt", AASSET_MODE_BUFFER);
    if (asset)
    {
        auto size = AAsset_getLength(asset);
        auto asset_buffer = AAsset_getBuffer(asset);
        auto file_list = String((const char*)asset_buffer, size).Replace("\r\n", "\n");
        files = file_list.Split("\n");

        AAsset_close(asset);
    }
    else
    {
        Debuger::Error("open file_list.txt in assets failed");
    }

    for (int i = 0; i < files.Size(); i++)
    {
        const auto& file = files[i];
		//Debuger::Log("open file_list:%s", file.c_str());
        asset = AAssetManager_open(mgr, file.c_str(), AASSET_MODE_BUFFER);
        if (asset)
        {
            auto size = AAsset_getLength(asset);
            auto asset_buffer = AAsset_getBuffer(asset);
            String dest_filename = dest + "/" + file;
            auto dir = dest_filename.Substring(0, dest_filename.LastIndexOf("/"));
            Directory::Create(dir);

			//Debuger::Log("WriteAllBytes:%s", dest_filename.c_str());
            File::WriteAllBytes(dest_filename, (byte*)asset_buffer, size);

            AAsset_close(asset);
        }
        else
        {
            Debuger::Error("open asset file:%s failed", file.c_str());
        }
    }
}
void android_extract_assets_if_needed(jobject asset_manager, const String& package_path, const String& data_path, bool always_extract)
{
	bool extract = false;

	auto version_file = data_path + "/version.txt";
	if (!File::Exist(version_file))
	{
		extract = true;
	}
	else
	{
		auto version = File::ReadAllText(version_file);
		if (version != "1.0.0")
		{
			extract = true;
		}
	}

	if (extract || always_extract)
	{
		Debuger::Log("extract Assets");

        extract_assets(asset_manager, "assets", data_path);

        File::WriteAllText(version_file, "1.0.0");
	}
	else
	{
		Debuger::Log("skip extract Assets");
	}
}
DC_END_NAMESPACE
#endif